query auteur($id: String!){
  auteur(id: $id){
    id
    nom
    prenom
    demandesEnvoyees {
      id
      personne {
        prenom
        nom
      }
    }
     demandesEnAttente {
      id
      personne {
        prenom
        nom
      }
    }
	}
}