query auteur($id: String!) {
  auteur(id: $id) {
    id
    nom
    prenom
    chat  {
      id
      canalId
    }
    demandesEnvoyees {
      id
      personne {
        prenom
        nom
      }
    }
    demandesEnAttente {
      id
      personne {
        prenom
        nom
      }
    }
    amis {
      id
      personne {
        prenom
        nom
      }
    }
  }
}